# game constants:
INITIAL_BALANCE = 1000
INITIAL_MPT = 0.2
INITIAL_PPT = 0.05 # in per cent
GOAL_BALANCE = 3000
COST_INCREASE_PER_TICK = 0.1
AVAILABLE_EFFECTS_SLOTS = 3

TICK = 1. # tick every TICK seconds
