# game constants:
INITIAL_BALANCE = 1500
INITIAL_MPT = 0.2
INITIAL_PPT = 0.05 # in per cent
GOAL_BALANCE = 3000
COST_INCREASE_PER_TICK = 0.1
AVAILABLE_EFFECTS_SLOTS = 3
BONUS_EVERY = 100 # ticks
BONUS_AMOUNT = 150
PER_BAKERY_EFFECT_BOOST = 5

TICK = 0.8  # tick every TICK seconds
